## Manual Clustering Exercise
Group datapoints into clusters based on provided attributes

Hidden patterns:
1) Customers can be clustered based on spending behavior:        
o High spenders with frequent purchases.        
o Moderate spenders with average income and frequency        .
o Low spenders with high income but infrequent purchas
2)  Clusters can also emerge based on age groups and income levels.

### Instructions
1. Formulate Similarity Metrics:    
o Define criteria for similarity (e.g., age proximity, income range
        spending score).    
o Consider which attributes are most relevant for clustering2
2. Group the Dat    a:
o Manually group the customers into 3â€“4 clusters based on their similariti    es.
o Use the given dataset and create clusters visually or by calcul
        ting differences be ween
va3ues.
3. Visualize the Clu    sters:
o Create a table or scatter plot (on paper or a spreadsheet) to sh
       w which c stomers
belong to which c4usters.
4. Summarize     Findings:
o Write a short explanation of the clustering criteria and insi
       hts gained from the clusters.es.

In [2]:
import pandas as pd

# Creating the dataset as a dictionary
data = {
    'Customer_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Age': [25, 34, 45, 23, 40, 29, 38, 31, 50, 21],
    'Income ($K)': [50, 60, 90, 20, 100, 45, 70, 55, 120, 30],
    'Spending_Score (1-100)': [80, 70, 30, 95, 25, 75, 50, 65, 20, 85],
    'Frequency_of_Purchase (per month)': [12, 9, 4, 15, 3, 10, 6, 8, 2, 14]
}

# Converting the dictionary to a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df

,Customer_ID,Age,Income ($K),Spending_Score (1-100),Frequency_of_Purchase (per month)
0,1,25,50,80,12
1,2,34,60,70,9
2,3,45,90,30,4
3,4,23,20,95,15
4,5,40,100,25,3
5,6,29,45,75,10
6,7,38,70,50,6
7,8,31,55,65,8
8,9,50,120,20,2
9,10,21,30,85,14

1. Similarity metrics
Age: Customers of a similar age may have similar spending habits
Income: Can indicate spending power and behavioural patterns
Spending score: indicates how much ppl r spending in rerlation to their income
Frequency of purchase: refelcts how frequently a customer makes a purchase


# Clustering strategy for spendig behaviour
Cluster 1 (High Spenders, Frequent Purchases):
    High Spending Score (Above 75)
    High Frequency of Purchases (Above 10)
Cluster 2 (Moderate Spenders, Average Income):
    Moderate Spending Score (50-75)
    Average Frequency of Purchases (6-10)
Cluster 3 (Low Spenders, Infrequent Purchases):
    Low Spending Score (Below 50)
    Low Frequency of Purchases (Below 6)
Cluster 4 (High Income, Low Frequency of Purchase):
    High Income ($70K and above)
    Low Frequency of Purchases (Below 6)

## Cluster 1
customers: 0,3,9
Their characteristics: 
    - spending score 80-95
    - Frequency: 12-15 purchases
    - Income: varies greatly from 20k-50k
    - Age: 25,23,21 - all young in age and similar age range

Insights: younger, have a lower income, and make many purchases. A tailored loyalty program and discounts would encourage them to keep spending

## Cluster 2
customers: 1,5,7
Their characteristics: 
    - spending score: 65-75
    - Frequency: 8-10 purchases
    - Income: 45k-60k
    - Age: 29-34. All similar age range, young
       
Insights: Still young, but older than the big spenders. Incomes are higher indicating the ability to afford more products when shopping. They are a steady and consistent customer base- new updates and products to the shop would keep them interested and engages

## Cluster 3
customers: 2,4,8
Their characteristics: 
    - spending score: 20-30
    - Frequency: 2-4 purchases
    - Income: 90-120k , very high income
    - Age: 40-50 . Older in age
    
Insights: Older, incomes are much higher. Yet they purchase much less. These individuals dont seem to feel the need to shop frequently at all. Perhaps special/limited edition products, or  marrketing tailored to them, or exclusive promotions would help encourage them to shop more

## Cluster 4
customers: 6
Their characteristics: 
    - spending score:50
    - Frequency: 5
    - Income: 70k
    - Age: 31
    
Insights: smaller group, income is still relatively high, the spending score is in the middle. We would need more observation of this group to determine their shopping habits